'use client';

import type { ParamSchema } from '@m8x/core';
import { Plus, X } from 'lucide-react';

import { Button, Field, Input, Select, Textarea } from '../ui';

export interface CredentialOption {
  id: string;
  name: string;
  type: string;
}

/**
 * Renders one parameter from its schema.
 *
 * Every node's inspector is generated by this function. That is the reason the
 * parameter schema exists at all: hand-writing a form per node is what makes
 * adding the eleventh node cost as much as the first.
 */
export function ParamField({
  schema,
  value,
  onChange,
  credentials,
}: {
  schema: ParamSchema;
  value: unknown;
  onChange: (value: unknown) => void;
  credentials: CredentialOption[];
}) {
  if (schema.credentialType) {
    const matching = credentials.filter((credential) => credential.type === schema.credentialType);
    return (
      <Field label={schema.displayName} hint={schema.description}>
        <Select value={String(value ?? '')} onChange={(event) => onChange(event.target.value || undefined)}>
          <option value="">None</option>
          {matching.map((credential) => (
            <option key={credential.id} value={credential.id}>
              {credential.name}
            </option>
          ))}
        </Select>
        {matching.length === 0 ? (
          <span className="block text-xs text-ink-faint">
            No credentials of this type yet. Add one under Credentials.
          </span>
        ) : null}
      </Field>
    );
  }

  switch (schema.type) {
    case 'boolean':
      return (
        <label className="flex cursor-pointer items-start gap-2.5 py-1">
          <input
            type="checkbox"
            checked={value === true}
            onChange={(event) => onChange(event.target.checked)}
            className="mt-0.5 size-4 accent-[var(--color-accent)]"
          />
          <span className="min-w-0">
            <span className="block text-xs font-medium text-ink">{schema.displayName}</span>
            {schema.description ? (
              <span className="block text-xs leading-relaxed text-ink-faint">{schema.description}</span>
            ) : null}
          </span>
        </label>
      );

    case 'select':
      return (
        <Field label={schema.displayName} hint={schema.description}>
          <Select value={String(value ?? '')} onChange={(event) => onChange(event.target.value)}>
            {schema.options?.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </Select>
        </Field>
      );

    case 'number':
      return (
        <Field label={schema.displayName} hint={schema.description}>
          <Input
            // Text rather than number, because these fields accept expressions
            // and a number input would silently reject `{{ $json.count }}`.
            type="text"
            inputMode="numeric"
            value={String(value ?? '')}
            placeholder={schema.placeholder}
            onChange={(event) => {
              const raw = event.target.value;
              const asNumber = Number(raw);
              onChange(raw !== '' && !raw.includes('{{') && Number.isFinite(asNumber) ? asNumber : raw);
            }}
          />
        </Field>
      );

    case 'code':
      return (
        <Field label={schema.displayName} hint={schema.description}>
          <Textarea
            rows={14}
            spellCheck={false}
            value={String(value ?? '')}
            onChange={(event) => onChange(event.target.value)}
            className="text-xs leading-relaxed"
          />
        </Field>
      );

    case 'json':
    case 'text':
      return (
        <Field label={schema.displayName} hint={schema.description}>
          <Textarea
            rows={schema.type === 'json' ? 6 : 3}
            spellCheck={false}
            value={String(value ?? '')}
            placeholder={schema.placeholder}
            onChange={(event) => onChange(event.target.value)}
            className="text-xs"
          />
        </Field>
      );

    case 'keyValue':
      return (
        <KeyValueList
          schema={schema}
          rows={Array.isArray(value) ? (value as Array<{ key?: string; value?: unknown }>) : []}
          onChange={onChange}
        />
      );

    default:
      return (
        <Field label={schema.displayName} hint={schema.description}>
          <Input
            value={String(value ?? '')}
            placeholder={schema.placeholder}
            onChange={(event) => onChange(event.target.value)}
          />
        </Field>
      );
  }
}

function KeyValueList({
  schema,
  rows,
  onChange,
}: {
  schema: ParamSchema;
  rows: Array<{ key?: string; value?: unknown }>;
  onChange: (value: unknown) => void;
}) {
  function update(index: number, patch: { key?: string; value?: unknown }) {
    onChange(rows.map((row, position) => (position === index ? { ...row, ...patch } : row)));
  }

  return (
    <div className="space-y-1.5">
      <span className="block text-xs font-medium text-ink-muted">{schema.displayName}</span>

      {rows.map((row, index) => (
        <div key={index} className="flex items-center gap-1.5">
          <Input
            value={row.key ?? ''}
            placeholder={schema.keyPlaceholder ?? 'name'}
            onChange={(event) => update(index, { key: event.target.value })}
            className="w-2/5"
          />
          <Input
            value={String(row.value ?? '')}
            placeholder={schema.valuePlaceholder ?? 'value'}
            onChange={(event) => update(index, { value: event.target.value })}
          />
          <Button
            variant="ghost"
            size="sm"
            className="shrink-0"
            onClick={() => onChange(rows.filter((_, position) => position !== index))}
            aria-label="Remove"
          >
            <X className="size-3.5" />
          </Button>
        </div>
      ))}

      <Button size="sm" variant="ghost" onClick={() => onChange([...rows, { key: '', value: '' }])}>
        <Plus className="size-3.5" />
        Add
      </Button>

      {schema.description ? (
        <span className="block text-xs leading-relaxed text-ink-faint">{schema.description}</span>
      ) : null}
    </div>
  );
}
